import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'mk-blue': '#007BFF',
        'mk-navy': '#002B5B',
        'mk-light-blue': '#E8F4FF',
        'mk-sky': '#4DAFFF',
        'mk-green': '#22C55E',
        'mk-dark-green': '#16A34A',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'hero-gradient': 'linear-gradient(135deg, #002B5B 0%, #007BFF 50%, #0056b3 100%)',
        'water-gradient': 'linear-gradient(180deg, #007BFF 0%, #4DAFFF 50%, #E8F4FF 100%)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        wave: { '0%, 100%': { transform: 'translateX(0)' }, '50%': { transform: 'translateX(-25%)' } },
        'wave2': { '0%, 100%': { transform: 'translateX(-25%)' }, '50%': { transform: 'translateX(0)' } },
        float: { '0%, 100%': { transform: 'translateY(0px)' }, '50%': { transform: 'translateY(-20px)' } },
        'float-delayed': { '0%, 100%': { transform: 'translateY(-10px)' }, '50%': { transform: 'translateY(10px)' } },
        bubble: { '0%': { transform: 'translateY(100%) scale(0)', opacity: '0' }, '50%': { opacity: '1' }, '100%': { transform: 'translateY(-100vh) scale(1.5)', opacity: '0' } },
        shimmer: { '0%': { backgroundPosition: '-200% 0' }, '100%': { backgroundPosition: '200% 0' } },
        'spin-slow': { from: { transform: 'rotate(0deg)' }, to: { transform: 'rotate(360deg)' } },
        marquee: { '0%': { transform: 'translateX(0%)' }, '100%': { transform: 'translateX(-50%)' } },
        'pulse-glow': { '0%, 100%': { boxShadow: '0 0 20px rgba(0,123,255,0.3)' }, '50%': { boxShadow: '0 0 40px rgba(0,123,255,0.8)' } },
        ripple: { '0%': { transform: 'scale(0)', opacity: '1' }, '100%': { transform: 'scale(4)', opacity: '0' } },
        'slide-up': { '0%': { transform: 'translateY(60px)', opacity: '0' }, '100%': { transform: 'translateY(0)', opacity: '1' } },
        'slide-in-left': { '0%': { transform: 'translateX(-60px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'slide-in-right': { '0%': { transform: 'translateX(60px)', opacity: '0' }, '100%': { transform: 'translateX(0)', opacity: '1' } },
        'fade-in': { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        'scale-in': { '0%': { transform: 'scale(0.8)', opacity: '0' }, '100%': { transform: 'scale(1)', opacity: '1' } },
        'droplet-fall': { '0%': { transform: 'translateY(-20px) scale(0)', opacity: '0' }, '50%': { opacity: '1' }, '100%': { transform: 'translateY(20px) scale(1)', opacity: '0' } },
        twinkle: { '0%, 100%': { opacity: '0.2', transform: 'scale(0.8)' }, '50%': { opacity: '1', transform: 'scale(1.2)' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        wave: 'wave 8s ease-in-out infinite',
        'wave2': 'wave2 10s ease-in-out infinite',
        float: 'float 6s ease-in-out infinite',
        'float-delayed': 'float-delayed 8s ease-in-out infinite',
        bubble: 'bubble 8s ease-in infinite',
        shimmer: 'shimmer 3s linear infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        marquee: 'marquee 25s linear infinite',
        'pulse-glow': 'pulse-glow 2s ease-in-out infinite',
        ripple: 'ripple 1s ease-out',
        'slide-up': 'slide-up 0.6s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.6s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.6s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'scale-in': 'scale-in 0.5s ease-out forwards',
        'droplet-fall': 'droplet-fall 2s ease-in-out infinite',
        twinkle: 'twinkle 3s ease-in-out infinite',
      },
      boxShadow: {
        'glass': '0 8px 32px rgba(0, 43, 91, 0.12)',
        'glass-hover': '0 16px 48px rgba(0, 123, 255, 0.25)',
        'card': '0 4px 24px rgba(0, 43, 91, 0.08)',
        'card-hover': '0 12px 40px rgba(0, 123, 255, 0.2)',
        'glow': '0 0 30px rgba(0, 123, 255, 0.4)',
        'glow-green': '0 0 30px rgba(34, 197, 94, 0.4)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
export default config;
